OBChat/OB/urls.py
"""
Determines the function in views.py to call when a request is received from a URL

See the Django documentation on the URL dispatcher for more information.
https://docs.djangoproject.com/en/3.0/topics/http/urls/
"""

from django.urls import re_path
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path
from django.views.generic.base import RedirectView

from OB.views.authentication import log_in, log_out, sign_up
from OB.views.room import chat, create_room, room
from OB.views.user import private, user

app_name = "OB"
urlpatterns = [
    re_path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico"), permanent=False),
        name="favicon",
    ),
    # Authentication
    path("log_in/", log_in, name="OB-log_in"),
    path("log_out/", log_out, name="OB-log_out"),
    path("sign_up/", sign_up, name="OB-sign_up"),
    # Room
    path("", chat, name="OB-/"),
    path("chat/", chat, name="OB-chat"),
    path("create_room/", create_room, name="OB-create_room"),
    re_path(r"^chat/(?P<room_name>[-\w]+)/$", room, name="OB-room"),
    # User
    re_path(r"^private/(?P<username>[-\w]+)/$", private, name="OB-private"),
    re_path(r"^user/(?P<username>[-\w]+)/$", user, name="OB-user"),
]

OBChat/OBChat/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [path("admin/", admin.site.urls), path("OB/", include("OB.urls"))]

OBChat/OB/models/models.py
"""
Models import organizer module. Holds all models classes to simplify models import statements.
Each of these classes is a model for a database object.
For each class in this file, there exists a table in the database.

See the Django documentation on Models for more information
https://docs.djangoproject.com/en/3.0/topics/db/models/
"""

# pylint: disable=unused-import
# Justification: The purpose of this module is simply to hold imports.

from OB.models.admin import Admin
from OB.models.ban import Ban
from OB.models.message import Message
from OB.models.ob_user import OBUser
from OB.models.room import Room

OBChat/OB/views/authentication.py
"""
Handles HTTP requests depending on the URL the request originated from (see urls.py)
Contains only the authentication views.

See the Django documentation on view functions for more information.
https://docs.djangoproject.com/en/3.0/topics/http/views/
"""

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from OB.models import OBUser


def sign_up(request):
    """
    Handles HTTP requests for the sign-up page.
    GETs the HTML template for the page.
    POSTs the user input in the form and returns errors or saves a new OBUser and redirects to
    the login page.

    Arguments:
        request (AsgiRequest)

    Return values:
        HTML Template: If GET or if POST and the form had errors.
        HTTP Response: If POST and no errors, an HTTP response redirecting to the login page.
    """

    if request.method == "GET":
        template = "OB/sign_up.html"
        return render(request, template)

    if request.method == "POST":
        # Organize form data
        username = request.POST["username"].strip()
        email = request.POST["email"].strip()
        password = request.POST["password"]
        display_name = request.POST["display_name"].strip()
        real_name = request.POST["real_name"].strip().split()
        birthday = request.POST["birthday"] or None

        context = {}

        # Check for errors
        if not all([username, email, password]):
            context["error_message"] = "Please fill out all required fields."
        elif " " in username:
            context["error_message"] = "Username may not contain spaces."
        elif " " in display_name:
            context["error_message"] = "Display name may not contain spaces."
        elif OBUser.objects.filter(username=username.lower()).exists():
            context["error_message"] = "Username already in use."
        elif OBUser.objects.filter(email=email).exists():
            context["error_message"] = "Email already in use."

        first_name = "" if not real_name else real_name[0]
        last_name = "" if len(real_name) <= 1 else " ".join(real_name[1:])

        # Return whichever info was valid to be put back in the form
        if "error_message" in context:
            template = "OB/sign_up.html"
            context.update(
                {
                    "username": username,
                    "email": email,
                    "display_name": display_name or None,
                    "first_name": first_name,
                    "last_name": last_name,
                    "birthday": birthday,
                }
            )
            return render(request, template, context)

        # If no display_name is entered and the username was not all lowercase, make the
        # case-sensitive version of the username the display_name
        if not display_name and not username.islower():
            display_name = username

        # Save a new OBUser to the database
        OBUser.objects.create_user(
            username=username.lower(),
            email=email,
            password=password,
            first_name=first_name,
            last_name=last_name,
            display_name=display_name,
            birthday=birthday,
        ).save()

        return HttpResponseRedirect(reverse("OB:OB-log_in"))

    # Not GET or POST
    return HttpResponse()


def log_in(request):
    """
    Handles HTTP requests for the login page.
    GETs the HTML template for the page.
    POSTs the user input in the form and returns errors or authenticates the user and redirects to
    the chat list page.

    Arguments:
        request (AsgiRequest)

    Return values:
        HTML Template: If GET or if POST and the form had errors.
        HTTP Response: If POST and no errors, an HTTP response redirecting to the login page.
    """

    template = "OB/log_in.html"

    if request.method == "GET":
        return render(request, template)

    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]

        # Log out the user if they are already authenticated
        if request.user.is_authenticated:
            logout(request)

        # Try to authenticate with the data given
        auth_user = authenticate(username=username.lower(), password=password)

        if auth_user is None:
            context = {
                "username": username,
                "error_message": "Invalid username or password.",
            }
            return render(request, template, context)

        login(request, auth_user)

        return HttpResponseRedirect(reverse("OB:OB-chat"))

    # Not GET or POST
    return HttpResponse()


def log_out(request):
    """
    Handles HTTP requests for the logout page.
    Logs the user out.

    Arguments:
        request (AsgiRequest)

    Return values:
        HTTP Response: An HTTP response redirecting to the login page.
    """

    if request.user.is_authenticated:
        logout(request)
    return HttpResponseRedirect(reverse("OB:OB-log_in"))

OBChat/OB/views/room.py
"""
Handles HTTP requests depending on the URL the request originated from (see urls.py)
Contains only the room views.

See the Django documentation on view functions for more information.
https://docs.djangoproject.com/en/3.0/topics/http/views/
"""

import json

from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils.safestring import mark_safe

from OB.constants import GroupTypes
from OB.models import Ban, Message, OBUser, Room
from OB.utilities.database import try_get
from OB.utilities.format import get_datetime_string


def chat(request):
    """
    Handles HTTP requests for the chat list page.
    GETs the HTML template for the page.

    Arguments:
        request (AsgiRequest)

    Return values:
        HTTP Response: The HTML template for the chat list.
    """

    if request.method == "GET":
        template = "OB/chat.html"
        context = {"rooms": Room.objects.filter(group_type=GroupTypes.Room)}
        return render(request, template, context)

    # Not GET
    return HttpResponse()


def create_room(request):
    """
    Handles HTTP requests for the room creation page.
    GETs the HTML template for the page.
    POSTs the user input in the form and returns errors or saves a new Room and redirects to
    the new room's page.

    Arguments:
        request (AsgiRequest)

    Return values:
        The HTML template if GET or if POST and the form had errors.
        An HTTP response redirecting to the new room's page if POST and no errors.
    """

    if request.method == "GET":
        if request.user.is_authenticated:
            template = "OB/create_room.html"
            context = {}
        else:
            template = "OB/log_in.html"
            context = {"error_message": "Must be logged in to create a room."}

        return render(request, template, context)

    if request.method == "POST":
        room_name = request.POST["room_name"].strip()
        display_name = request.POST["display_name"].strip() or None
        owner = OBUser.objects.get(username=request.user.username)

        context = {"room_name": room_name, "display_name": display_name}

        # Check for errors
        if not room_name:
            context["error_message"] = "Room must have a name."
        elif " " in room_name:
            context["error_message"] = "Room name cannot contain spaces."
        elif try_get(Room, group_type=GroupTypes.Room, name=room_name.lower()):
            context["error_message"] = "Room name already in use."
        elif display_name and " " in display_name:
            context["error_message"] = "Display name cannot contain spaces."

        # Return whichever info was valid to be put back in the form
        if "error_message" in context:
            template = "OB/create_room.html"
            return render(request, template, context)

        # If no display name is entered and the room name was not all lowercase, make the
        # case-sensitive version of the room name the display name
        if not display_name and not room_name.islower():
            display_name = room_name

        # Save the room to the database
        Room(name=room_name.lower(), display_name=display_name, owner=owner).save()

        return HttpResponseRedirect(reverse("OB:OB-room", kwargs={"room_name": room_name}))

    # Not GET or POST
    return HttpResponse()


def room(request, room_name):
    """
    Handles HTTP requests for the chat room page.
    GETs the HTML template for the page or an error page if it doesn't exist.

    Arguments:
        request (AsgiRequest)
        room_name (string): The name of the room which may or may not exist. Comes from the URL.

    Return values:
        HTML Template: If GET, returns the HTML template for the room or an error page if the room
            does not exist.
    """

    if request.method == "GET":
        room_object = try_get(Room, group_type=GroupTypes.Room, name=room_name)

        if room_object:
            websocket_url_json = mark_safe(json.dumps(f"ws://{{0}}/OB/chat/{room_name}/"))

            ban = try_get(
                Ban,
                user=request.user if request.user.is_authenticated else None,
                room=room_object,
            )
            messages_timestrings = []

            if not ban:
                # Get the messages
                message_query = Q(recipients=None)
                if request.user.is_authenticated:
                    message_query |= Q(recipients=request.user)
                messages = Message.objects.filter(message_query)

                for message in messages:
                    messages_timestrings += [(message, get_datetime_string(message.timestamp))]

            template = "OB/room.html"
            context = {
                "room": room_object,
                "websocket_url_json": websocket_url_json,
                "messages": messages_timestrings,
                "ban": ban,
            }
        else:
            # Return the room does not exist page
            template = "OB/not_room.html"
            context = {"room_name": room_name}

        return render(request, template, context)

    return HttpResponse()

OBChat/OB/views/user.py
"""
Handles HTTP requests depending on the URL the request originated from (see urls.py)
Contains only the user views.

See the Django documentation on view functions for more information.
https://docs.djangoproject.com/en/3.0/topics/http/views/
"""

import json

from django.http import HttpResponse
from django.shortcuts import render
from django.utils.safestring import mark_safe

from OB.constants import GroupTypes
from OB.models import Message, OBUser, Room
from OB.utilities.database import try_get
from OB.utilities.format import get_datetime_string, get_group_name


def user(request, username):
    """
    Handles HTTP requests for the user info page
    GETs the HTML template for the page or an error page if it doesn't exist
    POSTs the user input in the form and returns errors or saves the OBUser

    Arguments:
        request (AsgiRequest)
        username (string): The name of the user which may or may not exist.

    Return values:
        HTML Template: If GET or if POST and the form had errors, returns the HTML template for
            the room or an error page if the user does not exist.
        HTTP Response: An empty HTTP response if POST and no errors.
    """

    template = "OB/user.html"
    context = {"user": try_get(OBUser, username=username)}

    if request.method == "GET":
        if not context["user"]:
            template = "OB/not_user.html"

        return render(request, template, context)

    if request.method == "POST":
        # Ensure that only the user whose page this is can edit their information
        if request.user.username != username:
            return HttpResponse()

        # Organize all the data
        display_name = request.POST.get("display-name")
        real_name = request.POST.get("real-name")
        birthday = request.POST.get("birthday")

        # Check for errors
        if " " in display_name:
            context["error_message"] = "Display name may not contain spaces."

        if "error_message" in context:
            return render(request, template, context)

        # Display name
        if not display_name or display_name == request.user.display_name:
            request.user.display_name = None
        else:
            request.user.display_name = display_name.strip()

        # First and last names
        if real_name:
            split_name = real_name.strip().split()

            request.user.first_name = split_name[0]

            if len(split_name) > 1:
                request.user.last_name = " ".join(split_name[1:])
            else:
                request.user.last_name = ""

        # Birthday
        if birthday and birthday != request.user.birthday:
            request.user.birthday = birthday

        request.user.save()

        return render(request, template)

    # Not GET or POST
    return HttpResponse()


def private(request, username):
    """
    Handles HTTP requests for the private message page
    GETs the HTML template for the page or an error page if it doesn't exist

    Arguments:
        request (AsgiRequest)
        username (string): The name of the target user to private message.

    Return values:
        HTML Template: If GET, returns the HTML template for the room or an error page if the room
            does not exist.
    """

    if request.method == "GET":
        template = "OB/room.html"
        context = {}

        target_user = try_get(OBUser, username=username)

        if not request.user.is_authenticated:
            template = "OB/log_in.html"
            context = {"error_message": "Must be logged in to send private messages."}
        elif not target_user:
            template = "OB/not_user.html"
        else:
            private_room_name = get_group_name(GroupTypes.Private, request.user.id, target_user.id)
            room = try_get(Room, group_type=GroupTypes.Private, name=private_room_name)

            if not room:
                room = Room(group_type=GroupTypes.Private, name=private_room_name).save()

            # Get the messages
            websocket_url_json = mark_safe(json.dumps(f"ws://{{0}}/OB/private/{username}/"))
            messages = Message.objects.filter(room=room)
            messages_timestrings = [(message, get_datetime_string(message.timestamp)) for message in messages]

            template = "OB/room.html"
            context = {
                "room_name": room.name,
                "websocket_url_json": websocket_url_json,
                "messages": messages_timestrings,
            }

        return render(request, template, context)

    return HttpResponse()

OBChat/OB/templates/OB/base.html
<!-------------------------------------------------------------------------------------------------
A base template for all other templates to extend.
It contains the top navigation bar and bottom informational area of the website.
-------------------------------------------------------------------------------------------------->

<!doctype html>
<html lang="en">
<head>
  <!-- Meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <!-- JavaScript (Do not reorder) -->
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  {% block head %}
    <!-- <title>, <style>, other <script>, etc. -->
  {% endblock %}
</head>

<html>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'OB:OB-/' %}">OBChat</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <!-- Left-aligned items here -->
        </ul>
        {% if request.user.is_authenticated %}
          <div class="dropdown">
            <a class="btn btn-light dropdown-toggle" href="#" role="button" id="authUserDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <svg class="bi bi-people-circle" width="2em" height="2em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path d="M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 008 15a6.987 6.987 0 005.468-2.63z"/>
                <path fill-rule="evenodd" d="M8 9a3 3 0 100-6 3 3 0 000 6z" clip-rule="evenodd"/>
                <path fill-rule="evenodd" d="M8 1a7 7 0 100 14A7 7 0 008 1zM0 8a8 8 0 1116 0A8 8 0 010 8z" clip-rule="evenodd"/>
              </svg>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="authUserDropdown">
              <a class="dropdown-item" href="{% url 'OB:OB-user' username=request.user.username %}">User Info</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'OB:OB-log_out' %}">Log out</a>
            </div>
          </div>
        {% else %}
          <div class="dropdown">
            <a class="btn btn-light dropdown-toggle" href="#" role="button" id="anonUserDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <svg class="bi bi-person" width="2em" height="2em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z" clip-rule="evenodd"/>
              </svg>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
              <a class="dropdown-item" href="{% url 'OB:OB-log_in' %}">Log in</a>
              <a class="dropdown-item" href="{% url 'OB:OB-sign_up' %}">Sign up</a>
            </div>
          </div>
        {% endif %}
      </div>
    </nav>

    <div class="mx-3">
      {% block body %}
          <!-- Any content the extending template should contain -->
      {% endblock %}
    </div>
  </body>

  {% block javascript %}
    <!-- Oh boy, JavaScript! -->
  {% endblock%}
</html>

OBChat/OB/templates/OB/chat.html
<!-------------------------------------------------------------------------------------------------
Lists all the public chat rooms on the website
-------------------------------------------------------------------------------------------------->

{% extends "OB/base.html" %}

{% block head %}
  <title>
      Show me the rooms!
  </title>
{% endblock %}

{% block body %}
  <div class="row">
    <div class="mx-auto text-center">
      <h1>Choose your chat</h1>
      {% for room in rooms %}
        <a href="{% url 'OB:OB-room' room.name %}">{{ room.display_name }}</a><br>
      {% endfor %}
      <br>
      <a href="{% url 'OB:OB-create_room' %}"><strong>Create your own soverign room</strong></a>
    </div>
  </div>
{% endblock %}

OBChat/OB/templates/OB/create_room.html
<!-------------------------------------------------------------------------------------------------
Allows an authenticated user to create a new room
-------------------------------------------------------------------------------------------------->

{% extends "OB/base.html" %}

{% block head %}
  <title>
    OB a room
  </title>
{% endblock %}

{% block body %}
  <div class="row">
    <div class="mx-auto text-center">
      <h1>
        {% if not error_message %}
          It's aliiive!
        {% else %}
          Yikes
        {% endif %}
      </h1>

      {% if error_message %}
        <p><font color="red"><strong>{{ error_message }}</strong></font></p>
      {% endif %}

      <form action="{% url 'OB:OB-create_room' %}" method="post">
        {% csrf_token %}
        <p>Room Name</p>
        <input type="text" class="form-control" id="room-name" placeholder="obchat" style="max-width: 200px"
              value="{% if room_name %}{{ room_name }}{% endif %}">

        <br><hr>

        <p>Display Name</p>
        <input type="text" class="form-control" id="display-name" placeholder="OBChat" style="max-width: 200px"
              value="{% if display_name %}{{ display_name }}{% endif %}"><br><br>

        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
  </div>
{% endblock %}

OBChat/OB/templates/OB/log_in.html
<!-------------------------------------------------------------------------------------------------
Log-in page
-------------------------------------------------------------------------------------------------->

{% extends "OB/base.html" %}

{% block head %}
  <title>
    Secret Handshake
  </title>
{% endblock %}

{% block body %}
  <div class="row">
    <div class="mx-auto text-center">
      <h1>
        {% if not error_message %}
          What's the password?
        {% else %}
          You dun goof'd
        {% endif %}
      </h1>

      {% if error_message %}
        <p><font color="red"><strong>{{ error_message }}</strong></font></p>
      {% endif %}

      <form action="{% url 'OB:OB-log_in' %}" method="post">
        {% csrf_token %}
        <label>Username</label><br>
        <input type="text" name="username" placeholder="OB"
              value="{% if username %}{{ username }}{% endif %}"><br>

        <label>Password</label><br>
        <input type="password" name="password"><br><br>

        <input type="submit" value="Submit">
      </form><br>

      <p>You still don't have an account? <a href="{% url 'OB:OB-sign_up' %}">Click here to join the coolest site on the web!</a></p>
    </div>
  </div>
{% endblock %}

OBChat/OB/templates/OB/not_room.html
<!-------------------------------------------------------------------------------------------------
When a room with the name in the URL cannot be found
-------------------------------------------------------------------------------------------------->

{% extends "OB/base.html" %}

{% block head %}
  <title>
    A room for ghosts?
  </title>
{% endblock %}

{% block body %}
  <div class="row">
    <div class="mx-auto text-center">
      <h1>Nope!</h1>
      <p>We couldn't find that room for you. Maybe it's a ghost room...</p>
      <p>3spooky5me! <a href="{% url 'OB:OB-chat' %}">Run away!</a>
    </div>
  </div>
{% endblock %}

OBChat/OB/templates/OB/not_user.html
<!-------------------------------------------------------------------------------------------------
When a user with the username in the URL cannot be found
-------------------------------------------------------------------------------------------------->

{% extends "OB/base.html" %}

{% block head %}
  <title>
    Missing Person
  </title>
{% endblock %}

{% block body %}
  <div class="row">
    <div class="mx-auto text-center">
      <h1>Mysterious...</h1>
      <p>Nobody by that username exists in our database. They say a database never forgets.</p>
      <a href="{% url 'OB:OB-chat' %}">Time to chat with people who DO exist!</a>
    </div>
  </div>
{% endblock %}

OBChat/OB/templates/OB/sign_up.html
<!-------------------------------------------------------------------------------------------------
Sign-up page
-------------------------------------------------------------------------------------------------->

{% extends "OB/base.html" %}

{% block head %}
  <title>
    Good choice
  </title>
{% endblock %}

{% block body %}
  <div class="row">
    <div class="mx-auto text-center">
      <h1>Welcome to the club!</h1>

      {% if error_message %}
        <p><font color="red"><strong>{{ error_message }}</strong></font></p>
      {% endif %}

      <form action="{% url 'OB:OB-sign_up' %}" method="post">
        {% csrf_token %}
        <label>Username</label><br>
        <input type="text" name="username" placeholder="OB"
              value="{% if username %}{{ username }}{% endif %}"/><br>

        <label>Email</label><br>
        <input type="email" name="email" placeholder="kenji.ob.taka@gmail.com"
              value="{% if email %}{{ email }}{% endif %}"/><br>

        <label>Password</label><br>
        <input type="password" name="password"/><br>

        <br><hr>

        <label>Display Name</label><br>
        <input type="text" name="display_name" placeholder="OB"
              value="{% if display_name %}{{ display_name }}{% endif %}"/><br>

        <label>Real Name</label><br>
        <input type="text" name="real_name" placeholder="Kenji Takahashi-Rial"
              value="{% if first_name %}{{ first_name }}{% endif %} {% if last_name %}{{ last_name }}{% endif %}"/><br>

        <label>Birthday</label><br>
        <input type="date" name="birthday"
              value="{% if birthday %}{{ birthday }}{% endif %}"/><br><br><br>

        <button class="btn btn-primary" type="submit">Submit</button>
      </form>
    </div>
  </div>
{% endblock %}